### ISSUE TITLE
Port 8080 not free on 127.0.0.1

### ISSUE THREAD

**Issue by moshinh** [SVendittelli/MMM-fitbit#10]
So I've followed the instructions and all looks well until I run setup.    I get the below.  Any reason why?

Also do I need to do anything with the tokens.ini ?

25/Oct/2016:09:59:09] ENGINE Listening for SIGHUP.
[25/Oct/2016:09:59:09] ENGINE Listening for SIGTERM.
[25/Oct/2016:09:59:09] ENGINE Listening for SIGUSR1.
[25/Oct/2016:09:59:09] ENGINE Bus STARTING
CherryPy Checker:
The Application mounted at '' has an empty config.

[25/Oct/2016:09:59:09] ENGINE Started monitor thread 'Autoreloader'.
[25/Oct/2016:09:59:09] ENGINE Started monitor thread '_TimeoutMonitor'.
[25/Oct/2016:09:59:14] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x7666b7b0>>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/process/wspbus.py", line 205, in publish
    output.append(listener(*args, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpserver.py", line 168, in start
    ServerAdapter.start(self)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/process/servers.py", line 170, in start
    wait_for_free_port(*self.bind_addr)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/process/servers.py", line 439, in wait_for_free_port
    raise IOError("Port %r not free on %r" % (port, host))
IOError: Port 8080 not free on '127.0.0.1'

[25/Oct/2016:09:59:14] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/process/wspbus.py", line 243, in start
    self.publish('start')
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/process/wspbus.py", line 223, in publish
    raise exc
ChannelFailures: IOError("Port 8080 not free on '127.0.0.1'",)

[25/Oct/2016:09:59:14] ENGINE Bus STOPPING
[25/Oct/2016:09:59:14] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('127.0.0.1', 8080)) already shut down
[25/Oct/2016:09:59:14] ENGINE Stopped thread '_TimeoutMonitor'.
[25/Oct/2016:09:59:14] ENGINE Stopped thread 'Autoreloader'.
[25/Oct/2016:09:59:14] ENGINE Bus STOPPED
[25/Oct/2016:09:59:14] ENGINE Bus EXITING
[25/Oct/2016:09:59:14] ENGINE Bus EXITED

**Comment by moshinh** [comment]
Was running through ssh rather than from the terminal itself
