### ISSUE TITLE
Having issues installing.

### ISSUE THREAD

**Issue by tjop92** [SVendittelli/MMM-fitbit#9]
Hello.  I was hoping to get some help with installing the fitbit module for the Magic Mirror.  I am completely new to programming and am struggling to follow the directions.  I seem to be having issues installing the dependencies and how do I choose to clone the github files to the modules directory?  I also can't seem to get the setupAccess.py to work.  Is there a video or more thorough walk through for this module?  Any help is greatly appreciated.

**Comment by graaahn** [comment]
I have also had some problems when installing. I would not say that I'm completely new to programming, but quite rusty. I have a few questions.

- You (SVendittelli) say that we only need to save the client id and client secrete, but do we not need to save the Access/Refresh Token to write in the tokens.ini? Or should we leave this file completely empty?  

- When I run the setupAccess.py it seems to run for ever, and noting appears at neither fitbit.com or dev.fitbit.com. But you have written at the third to last step that we should allow access there? How do I do that?

**Comment by SVendittelli** [comment]
You're correct that you need to save the client ID and secret. The access and refresh tokens are saved automatically when the module successfully runs so you may leave that file empty.

When you run `setupAccess.py` you must do it on the Pi itself, it will not work via SSH. It will open a browser window on your Pi where you'll be asked to authorise your mirror to access your user data.

**Comment by graaahn** [comment]
Yeah, I'm on the PI, not on a SSH. Is the IP address that I should go to http://127.0.0.1:8080/? 
Because when I go to that webpage I only receive the message:

---------------------------------------------------------
404 Not Found

Missing parameters: state

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 67, in __call__
    raise sys.exc_info()[1]
HTTPError: (404, 'Missing parameters: state') 
---------------------------------------------------------

**Comment by Azrael-Masters** [comment]
I've got the same Issue with "2016-11-25-raspbian-jessie".
I think I have traced it down, that it is an Installation error of the python Shell.
I'm logged in on the BigScreen (not with SSH) and typing via Terminal:

```
pi@raspberrypi:~/MagicMirror/modules/MMM-fitbit $ npm install python-shell
/home/pi/MagicMirror/modules
└── python-shell@0.4.0
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/MagicMirror/modules/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/MagicMirror/modules/node_modules/node_helper/package.json'
npm WARN modules No description
npm WARN modules No repository field.
npm WARN modules No README data
npm WARN modules No license field.
```

I also tried this, without success:

```
pi@raspberrypi:~/MagicMirror $ npm install python-shell
magicmirror@2.0.0 /home/pi/MagicMirror
├── UNMET PEER DEPENDENCY grunt@1.0.1
└── python-shell@0.4.0
npm WARN grunt-yamllint@0.2.0 requires a peer of grunt@~0.4.0 but none was installed.
```


Anybody an Idea, what I need to do?

**Comment by izanbard** [comment]
@graaahn @Azrael-Masters 

I too was having issues in the install hanging at the `ENGINE Bus STARTED` point.

I got past it by not run as sudo:

`sudo python setupAccess.py <client_id> <secret>`

but used 

`python setupAccess.py <client_id> <secret>`

instead.

**Comment by pb3975** [comment]
@Azrael-Masters I am running into the same exact issue - I've also tried

`npm install grunt --save-dev`

Still no luck. I get this error

`grunt-yamllint@0.2.0 requires a peer of grunt@~0.4.0 but none was installed.`

**Comment by shbatm** [comment]
@izanbard Thanks. Not running as `sudo` worked for me!

**Comment by graaahn** [comment]
Not using sudo worked for me to! Thanks!!

**Comment by eried** [comment]
@graaahn I am getting the same error when browsing http://127.0.0.1:8080, I do not get the relation with setupAccess.py, what you did to fix it?

**Comment by dh1201** [comment]
Hello all,

Hoping that someone can lead me in the right direction.  Have followed the instructions through and all appeared to work correctly and the module is being displayed on the 'mirror' - however it does not update and shows 'zero' for all values.

config.js simply has:

```
		{
		        module: 'MMM-fitbit',
		        position: 'top_center',
		        config: {
			        credentials: {
				        client_id: 'ZZZZZZ',
			        	client_secret: 'zzzzzzzzzzzzzzzzzzzzzzzzzzz',
				},
			}
		},
```

have removed the actual client id and secret with 'z's for posting here.
at the last step the setupAccess.py <client_id> <secret> finished with a web page stating that all was OK; have checked my fitbit account an the application is showing as being authorised for read/write access.

Any help or suggestions would be greatly received - I am a Linux novice, so please assume nothing!!

**Comment by bradlindblad** [comment]
> I've got the same Issue with "2016-11-25-raspbian-jessie".
> I think I have traced it down, that it is an Installation error of the python Shell.
> I'm logged in on the BigScreen (not with SSH) and typing via Terminal:
> 
> ```
> pi@raspberrypi:~/MagicMirror/modules/MMM-fitbit $ npm install python-shell
> /home/pi/MagicMirror/modules
> └── python-shell@0.4.0
> npm WARN enoent ENOENT: no such file or directory, open '/home/pi/MagicMirror/modules/package.json'
> npm WARN enoent ENOENT: no such file or directory, open '/home/pi/MagicMirror/modules/node_modules/node_helper/package.json'
> npm WARN modules No description
> npm WARN modules No repository field.
> npm WARN modules No README data
> npm WARN modules No license field.
> ```
> I also tried this, without success:
> 
> ```
> pi@raspberrypi:~/MagicMirror $ npm install python-shell
> magicmirror@2.0.0 /home/pi/MagicMirror
> ├── UNMET PEER DEPENDENCY grunt@1.0.1
> └── python-shell@0.4.0
> npm WARN grunt-yamllint@0.2.0 requires a peer of grunt@~0.4.0 but none was installed.
> ```
> Anybody an Idea, what I need to do?

I also have an issue installing python-shell on Rasbian
